# Generated by Django 4.1.1 on 2022-10-29 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("getdatas", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="Veriler", new_name="Data",),
    ]
