# Generated by Django 4.1.1 on 2022-10-29 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("getdatas", "0002_rename_veriler_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="data",
            name="KULLANICI",
            field=models.OneToOneField(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
