# Generated by Django 4.1.1 on 2022-10-30 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("getdatas", "0005_remove_data_sira_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="data",
            name="ALICI_SIPARIS_NUMARASI",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="data",
            name="AMAZON_FEE",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="data",
            name="ASIN",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="data",
            name="KAR",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="data",
            name="SATICI_SIPARIS_NUMARASI",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="data",
            name="SATIS_FIYATI",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="data",
            name="TARIH",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="data",
            name="YUZDELIK_KAR",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
